server: "qbrp"

chat:
  channels:
    default:
      name: <white>Разговор
      format: "{author_name} {acoustic_separator} {acoustic_text}"
      acoustic:
        distort: true
      speech: true
      heads: true

    think:
      name: Мысли
      format: "<#404040>~ {author_name} ・ </#404040><#575757>{text}"
      distance: 10
      prefix: "~"
      heads: true

    admin:
      name: <red>Админ
      format: "{admin} {author_username} {dark_red_separator} {text}"
      global: true
      permission: true
      prefix: '$'
      notify: true

    gnrp:
      name: <#8986FF>Глобальный OOC
      format: "{nrp_br_open} {g} {gnrp_author_username} {gnrp_separator} {gnrp_text} {nrp_br_close}"
      global: true
      prefix: "-"

    lnrp:
      name: <#c9c9ff>Локальный OOC
      format: "{nrp_br_open} {l} {lnrp_author_username} {lnrp_separator} {lnrp_text} {nrp_br_close}"
      distance: 8
      prefix: "!"

    gm:
      name: <aqua>Чат с ГМами
      format: "{gm} {mentionable_author_username} {dark_red_separator} {text} <dark_gray>({author_name})</dark_gray>"
      permission: true
      global: true
      prefix: "*"
      notify: true

    spectator:
      name: <light_purple>Наблюдатели
      format: "{spec} {author_username} {light_purple_separator} {text}"
      distance: 32
      prefix: "№"
      spectator: true

  commands:
    me:
      name: <green>Действие
      format: "{author_name} {yellow_star} {text}"
      distance: 12
      regex:
        exp: '^\*\*.*\*\*$'
        remove: '\*\*'
      heads: true
    roll:
      format: "{author_name} {aqua_star} {text} {aqua_dash} {roll}"
      distance: 12
      heads: true
      invoke_permission: true
    do:
      format: "{author_name} {do}"
      distance: 12
      heads: true
    doo:
      format: "{author_name} {do}"
      distance: 32
      heads: true
    dooo:
      format: "{author_name} {do}"
      distance: 64
      heads: true
    gdo:
      format: "{purple_bold_star} {author_name} {do}"
      global: true
      heads: true

  placeholders:
    roll: "<green>{random-100}%</green>"
    purple_bold_star: "<bold><light_purple>*</light_purple></bold>"
    yellow_star: "<yellow>*</yellow>"
    aqua_star: "<aqua>*</aqua>"
    aqua_dash: "<aqua>—</aqua>"
    do: "{purple_br_open} {text} {purple_br_close}"
    purple_br_open: "<light_purple>(</light_purple>"
    purple_br_close: "<light_purple>)</light_purple>"
    brown_br_open: "<#554436>((</#554436>"
    brown_br_close: "<#554436>))</#554436>"
    pm: "<#F4A460><bold>ᴘᴍ</bold></#F4A460>"
    brown_arrow: "<#F4A460>▸</#F4A460>"
    brown_dots: "<#F4A460>:</#F4A460>"
    gray_author_name: "<gray>{author_username}</gray>"
    gray_recipient_name: "<gray>{pm_receiver_username}</gray>"
    dark_red_separator: "<dark_red>▸</dark_red>"
    acoustic_separator: "<{separator_color}>▸</{separator_color}>"
    acoustic_text: "<{color}>{bold1|}{text}{bold2|}</{color}>"
    admin: "<dark_red><bold>ADMIN</bold></dark_red>"
    spec: "<light_purple><bold>SPEC</bold></light_purple>"
    light_purple_separator: "<light_purple>▸</light_purple>"

    gm: "<#4673e1><bold>GM</bold></#4673e1>"
    mentionable_author_username: "<hover:show_text:'Кликните, удерживая <bold>SHIFT</bold>, чтобы вставить упоминание игрока'><insert:*@{author_username} >{author_username}</insert></hover>"

    nrp_br_open: "<#282833>((</#282833>"
    nrp_br_close: "<#282833>))</#282833>"

    gnrp_author_username: "<#44437f>{author_username}</#44437f>"
    gnrp_separator: "<#8986FF>▸</#8986FF>"
    gnrp_text: "<#6d6bcc>{text}</#6d6bcc>"
    g: "<#8986FF><bold>ɢ</bold></#8986FF>"

    lnrp_author_username: "<#787899>{author_username}</#787899>"
    lnrp_separator: "<#c9c9ff>▸</#c9c9ff>"
    lnrp_text: "<#a0a0cc>{text}</#a0a0cc>"
    l: "<#c9c9ff><bold>ɢ</bold></#c9c9ff>"

    separator_color: "gray"
    color: "white"

  default-channel: "default"

  pm: "{brown_br_open} {pm} {gray_author_name} {brown_arrow} {gray_recipient_name} {brown_dots} <gray>{text}</gray> {brown_br_close}"

  acoustic:
    passability:
      solid: 0.01
      partial: 0.9
      air: 1
      tags:
        "minecraft:doors": 0.7
    formatting:
      - volume: 0.0
        multiplier: 0.5
        input_placeholders:
          separator_color: "yellow"
        output_placeholders:
          color: '#555555'
      - volume: 0.1
        multiplier: 0.7
        input_placeholders:
          separator_color: "yellow"
        output_placeholders:
          color: '#AAAAAA'
      - volume: 0.3
        input_placeholders:
          separator_color: "gray"
        output_placeholders:
          color: "#FFFFFF"
      - volume: 0.55
        input_placeholders:
          separator_color: "red"
        output_placeholders:
          color: "red"
      - volume: 1
        input_placeholders:
          separator_color: "dark_red"
        output_placeholders:
          color: "red"
          bold1: "<bold>"
          bold2: "</bold>"
    distortion:
      threshold: 0.3
      artifacts: [ '-', '~' ]
    simulation:
      range: 24
      performance-debug: false
      rebuild-debug: false
    volume:
      max: 10
      hearing-threshold: 0.07
      attenuation: 0.9

  join:
    enabled: false
    message: ""
  leave:
    enabled: false
    message: ""
  advancements: false

player:
  volume:
    min: 0.3
    base: 0.5
    max: 1.2
  attributes:
    default:
      speed: 0.12
      jump-strength: 0.45
    gm:
      speed: 0.24
      jump-strength: 0.45
    spectator:
      speed: 0.15
  damage: true

vocal:
  # При каком значении усталости возможно сорвать голос
  break_threshold: 0.3
  # Шанс сорвать голос при максимальной усталости
  break_chance: 0.1
  # Время восстановления голоса при срыве в секундах
  regeneration_time: 700
  # Случайный разброс времени
  regeneration_random: 0.5

  # Выше какой громкости голосовой аппарат начинает уставать
  tiredness_threshold: 0.6
  # Усиление усталости голоса при полной громкости (до 1)
  tiredness_gain: 0.125
  # Уменьшение усталости голоса в секунду (при 0.33 выходит 600 секунд, примерно 10 минут)
  tiredness_decrease_rate: 0.0033

movement:
  # Множитель скорости в режиме бега
  sprint_multiplier: 1.5
  # Множитель к показателю аттрибута скорости, определяющий самую низкую возможную скорость (от 0 до 1)
  min_speed_factor: 0.05
  # Минимально возможная скорость при беге, работает как минимальный ограничитель множителя регулируемой игроком скорости
  min_speed_multiplier_sprint_factor: 0.3

  stamina: true
  jump_stamina_consume: 0.25
  # Уменьшение стамины за 1 минуту при максимальной скорости
  stamina_consumption: 5.3
  # Постоянное (!) восстановление стамины за 1 минуту. Стамина тратится, когда потребление становится больше регенерации
  stamina_regen: 5.6
  # Порог стамины, при котором персонаж начинает замедляться
  slowdown_stamina_threshold: 0.3

  # Как сильно скорость, регулируемая игроков, влияет на реальную скорость персонажа (по сути, ограничитель)
  intention_effect: 0.7

item_autosave_period: 120
