connection:
  #Minimum value: 3, Maximum value: 180, Default value: 15
  skin_download_retry_delay: 15
auth:
  #Default value: false
  auto_login: false
chat:
  #Minimum value: 0, Maximum value: 600, Default value: 340
  width: 340
  #Minimum value: 0, Maximum value: 5000, Default value: 300
  size: 300
chat-bubbles:
  #Default value: true
  enabled: true
  #Minimum value: 0.01, Maximum value: 3.0, Default value: 1.0
  scale: 1.0
  #Minimum value: 1.0, Maximum value: 10.0, Default value: 1.9
  height: 1.9
  #Minimum value: 50, Maximum value: 1000, Default value: 200
  line-width: 200
  #Minimum value: 2, Maximum value: 2400, Default value: 200
  life-time: 200
  #Minimum value: 0, Maximum value: 100, Default value: 50
  background-opacity: 50
  #Default value: true
  hiding: true
  #Default value: true
  ignore-light-level: false
chat-input:
  #Minimum value: 0.0, Maximum value: 5.0, Default value: 3.0
  shaking-force: 3.0
  #Minimum value: 0.0, Maximum value: 1.0, Default value: 0.5
  shaking-threshold: 0.5
  #Default value: false
  closing: false
ui:
  #Default value: false
  indicator-visible: false
  #Default value: false
  hotbar-visible: false
visual:
  #Minimum value: 4, Maximum value: 16, Default value: 6
  easing-distance: 6
