max-distance=0
max-speed=2
camera=true
tripod=true
player-control=true
custom-speed=true
creative-flight=true
custom-perspective=true
hide-player=true
show-hand=true
disable-on-damage=true
notifications=true
noclip=false
ignore-transparent=false
ignore-openable=false
ignore-custom=false
freeze-player=false
interaction=false
full-bright=false
hide-submersion-fog=false
outline-player=false
unloaded-chunks=false
voice-camera=false
